export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
